config/routes.rb
Rails.application.routes.draw do
  root to: 'divisions#index'
  resources :divisions do
    resources :employees
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
  has_many :employees, dependent: :destroy
   validates :name, presence: true
    validates_length_of :name, maximum: 100
    before_save(:titleize_division)

 private
   def titleize_division
     self.name = self.name.titleize
   end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :division
  validates :name, presence: true
   validates_length_of :name, maximum: 100
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController

  def index
    @divisions = Division.all
    render :index
  end

  def new
    @division = Division.new
    render :new
  end

  def create
    @division = Division.new(division_params)
    if @division.save
      flash[:notice] = "New Division successfully added!"
      redirect_to divisions_path
    else
      render :new
    end
  end


  def edit
    @division = Division.find(params[:id])
    render :edit
  end

  def show
    @division = Division.find(params[:id])
    render :show
  end

  def update
    @division= Division.find(params[:id])
    if @division.update(division_params)
      redirect_to divisions_path
    else
      render :edit
    end
  end

  def destroy
    @division = Division.find(params[:id])
    @division.destroy
    redirect_to divisions_path
  end
  def show
    @division = Division.find(params[:id])
    render :show
  end
  def update
    @division= Division.find(params[:id])
    if @division.update(division_params)
      redirect_to divisions_path
    else
      render :edit
    end
  end
  def destroy
    @division = Division.find(params[:id])
    @division.destroy
    redirect_to divisions_path
  end
  private
  def division_params
    params.require(:division).permit(:name)
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @division = Division.find(params[:division_id])
    @employee = @division.employees.new
    render :new
  end

  def create
    @division = Division.find(params[:division_id])
    @employee = @division.employees.new(employee_params)
    if @employee.save
      redirect_to division_path(@division)
    else
      render :new
    end
  end

  def show
    @division = Division.find(params[:division_id])
    @employee = Employee.find(params[:id])
    render :show
  end

  def edit
    @division = Division.find(params[:division_id])
    @employee = Employee.find(params[:id])
    render :edit
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to division_path(@employee.division)
    else
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to division_path(@employee.division)
  end
  # Other controller actions go here.

  private
  def employee_params
    params.require(:employee).permit(:name, :lyrics)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/divisions/edit.html.erb
<h1>Edit division</h1>

<%= render "layouts/division_form" %>

app/views/divisions/index.html.erb
<h1>Divisions</h1>

<% if @divisions.any? %>
  <ul>
    <% @divisions.each do |division| %>
      <li><%= link_to division.name, division_path(division) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no divisions yet.</p>
<% end %>


<p><%= link_to "Create new division", new_division_path %></p>

app/views/divisions/new.html.erb
<h1>New division</h1>
<%= render "layouts/division_form" %>

app/views/divisions/show.html.erb
<h1><%= @division.name %></h1>

<% if @division.employees.any? %>
  <h4>Here are the employees for this division:</h4>

  <% @division.employees.each do |employee| %>
    <ul>
      <li>
        <%= link_to employee.name, division_employee_path(@division, employee) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No employees are listed for this division.</p>
<% end %>

<p><%= link_to "Add a employee", new_division_employee_path(@division) %></p>

<p><%= link_to "Edit", edit_division_path(@division) %></p>
<p><%= link_to "Delete division", division_path(@division),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to divisions", divisions_path %></p>

app/views/employees/edit.html.erb
<h1>Edit employee:</h1>

<%= form_for [@division, @employee] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/employees/new.html.erb
<h1>Add a new employee:</h1>

<%= render "layouts/employee_form" %>

app/views/employees/show.html.erb
<h1>Employee: <%= @employee.name %></h1>
<h2>Division: <%= @division.name %></h2>


<p><%= link_to "Edit employee", edit_division_employee_path(@division, @employee) %></p>
<p><%= link_to "Delete employee", division_employee_path(@division, @employee),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to division", division_path(@division) %></p>

app/views/layouts/_division_form.html.erb
<%= render "layouts/errors", :object => @division %>

<%= form_for @division do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/layouts/_employee_form.html.erb
<%= render "layouts/errors", :object => @employee %>
<%= form_for [@division, @employee] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsEmployeeTracker</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= flash[:alert] %>
  <%= flash[:notice] %>

  <%= yield %>
</body>
</html>